services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=https://debian-server.tail7b7869.ts.net
      - ASSET_URL=https://debian-server.tail7b7869.ts.net
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
      - VITE_APP_NAME=Laravel

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"