services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWER}/mining-technical-test:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=debian-server.tail7b7869.ts.net:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
      - VITE_APP_NAME=Laravel
    volumes:
      - ./database:/var/www/html/database/

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - ./database:/var/lib/grafana/laravel-monitor:ro
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:     
