name: Continuous Integration & Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Temporarily connect GitHub Actions runner to your Tailnet
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # 2. Set up SSH key for authenticating into your server
      - name: Set up SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to debian server via tailscale
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEBIAN_HOST_IP }}
          username: ${{ secrets.DEBIAN_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            set -e 
            cd ~/projects/mining-technical-test
            git fetch origin main
            git reset --hard origin/main
            export GITHUB_REPOSITORY_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            GITHUB_REPOSITORY_OWNER_LOWER=$GITHUB_REPOSITORY_OWNER_LOWER docker compose down
            GITHUB_REPOSITORY_OWNER_LOWER=$GITHUB_REPOSITORY_OWNER_LOWER docker compose up -d --build --remove-orphans
            docker image prune -f
          